mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mySite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='詳細資料'),
    path('<int:question_id>/results/', views.results, name='投票結果'),
    path('<int:question_id>/vote/', views.vote, name='投票')
]

mySite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
        # How are you

    def was_published_recently(self):
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        return timezone.now() - self.pub_date <= datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mySite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Question

# Create your views here.

def index(request):
	# response = HttpResponse('Hello, here is the index.')
	# return response
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	# output = ', '.join([q.question_text for q in latest_question_list])
	# return HttpResponse(output)
	context = {'latest_question_list': latest_question_list}
	return render(request, 'polls/index.html', context)

def detail(request, question_id):
	# return HttpResponse('這是 %s 的詳細頁面' % question_id)
	# try:
	# 	question = Question.objects.get(pk = question_id)
	# except Question.DoesNotExist:
	# 	raise Http404("這個問題並不存在！")

	question = get_object_or_404(Question, pk=question_id)

	question = Question.objects.filter(pk=question_id)
	if len(question) == 0:
		return render(request, 'polls/detail.html', {'question': '沒有東西'})
	else:
		return render(request, 'polls/detail.html', {'question': question[0]})

	return render(request, 'polls/detail.html', {'question':question})


def results(request, question_id):
	response = '這是第 %s 個問題的投票結果。'
	return HttpResponse(response % question_id)

def vote(request, question_id):
	response = '投票給第 %d 個問題' % question_id
	return HttpResponse(response)

mySite/polls/templates/polls/detail.html
<h1>問題描述：</h1>
<h2>{{question.question_text}}</h2>

<ul>
	{% for choice in question.choice_set.all %}
		<li>
			{{ choice.choice_text }}
		</li>
	{% endfor %}
</ul>

mySite/polls/templates/polls/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>問題頁面</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h1>問題頁面</h1>



<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">標題</th>

    </tr>
  </thead>
  <tbody>

    {% if latest_question_list %}
    {% for question in latest_question_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></td>
    </tr>
    {% endfor %}
    {% endif %}


  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>